### ISSUE TITLE
Cannot Create Currencies

### ISSUE THREAD

**Issue by ethernia-root** [Dans-Plugins/Currencies#170]
## Cannot Create Currency

Paper 1.18.2 / Both MF and C latest!

Java 17

[Log](https://www.toptal.com/developers/hastebin/zeputevapi.properties)

**Comment by dmccoystephenson** [comment]
Thanks for letting me know!

**Comment by dmccoystephenson** [comment]
It looks like the Medieval Factions API can't be found for some reason.

**Comment by a-emulus** [comment]
whats the fix?
