### ISSUE TITLE
Prompt the user to rename the item when creating a currency (if the item already has a display name)

### ISSUE THREAD

**Issue by alyphen** [Dans-Plugins/Currencies#176]
Users who are used to Currencies 1 like that the item would automatically name to the currency name. We should prompt users to rename the item when creating a currency before it is created, allowing users the choice between the existing name of the item or another name.

**Comment by dmccoystephenson** [comment]
Rather than prompt the user, it would be simpler to automatically name the item to the currency name. I'd like to go for that for now and move this to the v2.1.0 milestone.

I've created #180 for this.

**Comment by alyphen** [comment]
> Rather than prompt the user, it would be simpler to automatically name the item to the currency name. I'd like to go for that for now and move this to the v2.1.0 milestone.
> 
> I've created #180 for this.

I think this is simple enough - when creating a currency, a conversation can be used with a BooleanPrompt.
We could potentially only show it when the item has a display name, and default to renaming all items with no display name.
